package gui;

import javax.swing.*;
import java.awt.*;

public class Home {
    private JPanel panel;
    private JPanel bacheca1;
    private JPanel bacheca2;
    private JPanel bacheca3;
    private JLabel titolo1;
    private JLabel titolo2;
    private JLabel titolo3;
    private JButton buttonAddToDo1;
    private JButton buttonAddToDo2;
    private JButton buttonAddToDo3;
    private JList list1;
    private JButton exitButton;

    public static void main(String[] args) {
        JFrame frame = new JFrame("Home");
        frame.setContentPane(new Home().panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        bacheca1 = new JPanel();
        bacheca1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel.add(bacheca1);
        titolo1 = new JLabel();
        titolo1.setText("Lavoro");
        bacheca1.add(titolo1);
        buttonAddToDo1 = new JButton();
        buttonAddToDo1.setText("Add To DO");
        bacheca1.add(buttonAddToDo1);
        list1 = new JList();
        bacheca1.add(list1);
        bacheca2 = new JPanel();
        bacheca2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(bacheca2);
        titolo2 = new JLabel();
        titolo2.setText("Universita");
        bacheca2.add(titolo2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 2, false));
        buttonAddToDo2 = new JButton();
        buttonAddToDo2.setText("Add To Do");
        bacheca2.add(buttonAddToDo2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bacheca3 = new JPanel();
        bacheca3.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(bacheca3);
        titolo3 = new JLabel();
        titolo3.setText("Tempo Libero");
        bacheca3.add(titolo3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonAddToDo3 = new JButton();
        buttonAddToDo3.setText("Add To Do");
        bacheca3.add(buttonAddToDo3, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        exitButton = new JButton();
        exitButton.setText("Exit");
        panel.add(exitButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
